version: '3.8'

services:
  server:
    build: ./server
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 5000:5000

  client:
    depends_on:
      - server
    build: ./client
    env_file: ./client/.env
    ports:
      - 3000:80

